matrix:
  model.id:
  - flow/agcrn
  - flow/astgcn
  - flow/d2stgnn
  - flow/dcrnn
  - flow/dgcrn
  - flow/dstagnn
  - flow/energymamba
  - flow/gluonts
  - flow/gwnet
  - flow/healthmamba
  - flow/hl
  - flow/mamba
  - flow/patchtst
  - flow/st_llm_plus
  - flow/stgcn
  - flow/stgode
  - flow/sttn
  - flow/trustenergy
  - flow/uqgnn
  data.version:
  - 2025_12to1
  training.seed:
  - 2026
overrides: {}
runs:
- ../runs/dc_60min/flow_hl.yaml
devices: all
