matrix:
  data.version:
  - 2025_12to1
  training.seed:
  - 2026
overrides: {}
runs:
- ../runs/dc_od_60min/od_agcrn.yaml
- ../runs/dc_od_60min/od_astgcn.yaml
- ../runs/dc_od_60min/od_gwnet.yaml
- ../runs/dc_od_60min/od_hl.yaml
- ../runs/dc_od_60min/od_odmixer.yaml
- ../runs/dc_od_60min/od_stpro.yaml
- ../runs/dc_od_60min/od_od_ced.yaml
- ../runs/dc_od_60min/od_stgcn.yaml
- ../runs/dc_od_60min/od_stgode.yaml
- ../runs/dc_od_60min/od_stzinb.yaml
devices: all
