matrix:
  data.version:
  - 2025_12to1
  training.seed:
  - 2026
overrides: {}
runs:
- ../runs/dc_od_60min/od_agcrn.yaml
- ../runs/dc_od_60min/od_astgcn.yaml
- ../runs/dc_od_60min/od_gwnet.yaml
- ../runs/dc_od_60min/od_hl.yaml
- ../runs/dc_od_60min/od_odmixer.yaml
- ../runs/dc_od_60min/od_stpro.yaml
- ../runs/dc_od_60min/od_od_ced.yaml
- ../runs/dc_od_60min/od_pdr.yaml
- ../runs/dc_od_60min/od_pdr_no_context.yaml
- ../runs/dc_od_60min/od_pdr_no_moe.yaml
- ../runs/dc_od_60min/od_pdr_no_spatial.yaml
- ../runs/dc_od_60min/od_pdr_no_zone_embed.yaml
- ../runs/dc_od_60min/od_pdr_reg.yaml
- ../runs/dc_od_60min/od_pdr_reg_gau.yaml
- ../runs/dc_od_60min/od_pdr_reg_lap.yaml
- ../runs/dc_od_60min/od_pdr_reg_t.yaml
- ../runs/dc_od_60min/od_stgcn.yaml
- ../runs/dc_od_60min/od_stgode.yaml
- ../runs/dc_od_60min/od_stzinb.yaml
devices: all
