runs:
- ../runs/dc_od_60min_bike/od_hl.yaml
- ../runs/nyc_manhattan_od_15min_fhv/od_hl.yaml
- ../runs/nyc_manhattan_od_15min_taxi/od_hl.yaml
- ../runs/chicago_od_15min_tnp/od_hl.yaml
- ../runs/chicago_od_15min_taxi/od_hl.yaml
- ../runs/chicago_od_15min_bike/od_hl.yaml
- ../runs/dc_od_60min_bike/od_agcrn.yaml
- ../runs/nyc_manhattan_od_15min_fhv/od_agcrn.yaml
- ../runs/nyc_manhattan_od_15min_taxi/od_agcrn.yaml
- ../runs/chicago_od_15min_tnp/od_agcrn.yaml
- ../runs/chicago_od_15min_taxi/od_agcrn.yaml
- ../runs/chicago_od_15min_bike/od_agcrn.yaml
- ../runs/dc_od_60min_bike/od_astgcn.yaml
- ../runs/nyc_manhattan_od_15min_fhv/od_astgcn.yaml
- ../runs/nyc_manhattan_od_15min_taxi/od_astgcn.yaml
- ../runs/chicago_od_15min_tnp/od_astgcn.yaml
- ../runs/chicago_od_15min_taxi/od_astgcn.yaml
- ../runs/chicago_od_15min_bike/od_astgcn.yaml
- ../runs/dc_od_60min_bike/od_gwnet.yaml
- ../runs/nyc_manhattan_od_15min_fhv/od_gwnet.yaml
- ../runs/nyc_manhattan_od_15min_taxi/od_gwnet.yaml
- ../runs/chicago_od_15min_tnp/od_gwnet.yaml
- ../runs/chicago_od_15min_taxi/od_gwnet.yaml
- ../runs/chicago_od_15min_bike/od_gwnet.yaml
- ../runs/dc_od_60min_bike/od_stgcn.yaml
- ../runs/nyc_manhattan_od_15min_fhv/od_stgcn.yaml
- ../runs/nyc_manhattan_od_15min_taxi/od_stgcn.yaml
- ../runs/chicago_od_15min_tnp/od_stgcn.yaml
- ../runs/chicago_od_15min_taxi/od_stgcn.yaml
- ../runs/chicago_od_15min_bike/od_stgcn.yaml
- ../runs/dc_od_60min_bike/od_stgode.yaml
- ../runs/nyc_manhattan_od_15min_fhv/od_stgode.yaml
- ../runs/nyc_manhattan_od_15min_taxi/od_stgode.yaml
- ../runs/chicago_od_15min_tnp/od_stgode.yaml
- ../runs/chicago_od_15min_taxi/od_stgode.yaml
- ../runs/chicago_od_15min_bike/od_stgode.yaml
- ../runs/dc_od_60min_bike/od_stzinb.yaml
- ../runs/nyc_manhattan_od_15min_fhv/od_stzinb.yaml
- ../runs/nyc_manhattan_od_15min_taxi/od_stzinb.yaml
- ../runs/chicago_od_15min_tnp/od_stzinb.yaml
- ../runs/chicago_od_15min_taxi/od_stzinb.yaml
- ../runs/chicago_od_15min_bike/od_stzinb.yaml
- ../runs/dc_od_60min_bike/od_odmixer.yaml
- ../runs/nyc_manhattan_od_15min_fhv/od_odmixer.yaml
- ../runs/nyc_manhattan_od_15min_taxi/od_odmixer.yaml
- ../runs/chicago_od_15min_tnp/od_odmixer.yaml
- ../runs/chicago_od_15min_taxi/od_odmixer.yaml
- ../runs/chicago_od_15min_bike/od_odmixer.yaml
- ../runs/dc_od_60min_bike/od_stpro.yaml
- ../runs/nyc_manhattan_od_15min_fhv/od_stpro.yaml
- ../runs/nyc_manhattan_od_15min_taxi/od_stpro.yaml
- ../runs/chicago_od_15min_tnp/od_stpro.yaml
- ../runs/chicago_od_15min_taxi/od_stpro.yaml
- ../runs/chicago_od_15min_bike/od_stpro.yaml
- ../runs/dc_od_60min_bike/od_od_ced.yaml
- ../runs/nyc_manhattan_od_15min_fhv/od_od_ced.yaml
- ../runs/nyc_manhattan_od_15min_taxi/od_od_ced.yaml
- ../runs/chicago_od_15min_tnp/od_od_ced.yaml
- ../runs/chicago_od_15min_taxi/od_od_ced.yaml
- ../runs/chicago_od_15min_bike/od_od_ced.yaml
matrix:
  training.seed:
  - 2026
devices: all
