model:
  id: flow/dcrnn
  params:
    n_filters: 64
    max_diffusion_step: 2
    filter_type: doubletransition
    num_rnn_layers: 2
    cl_decay_steps: 2000
  name: DCRNN
training:
  optimizer:
    name: Adam
    lr: 0.01
    weight_decay: 0
  scheduler:
    name: MultiStepLR
    milestones:
    - 10
    - 50
    - 90
    gamma: 0.1
  clip_grad_norm: 5
