model:
  id: flow/gwnet
  params:
    adj_type: doubletransition
    adp_adj: 1
    init_dim: 32
    skip_dim: 256
    end_dim: 512
    dropout: 0.3
  name: GWNET
training:
  optimizer:
    name: Adam
    lr: 0.001
    weight_decay: 0.0001
  scheduler:
    name: StepLR
    step_size: 200
    gamma: 0.95
  clip_grad_norm: 5
