model:
  id: od/pdr_reg
data:
  id: dc_od_60min_bike
experiment:
  name: dc_od_60min_bike_od_split
runtime:
  mode: calibrate
  checkpoint: null
calibration:
  mode: horizon
  method: split
output:
  predictions: true
