model:
  id: od/od_ced
  name: OD-CED_OD
  params:
    embed_dim: 64
    num_heads: 4
    dense_quantile: 0.85
    coarsening_max_iter: 100
    coarsening_tolerance: 0.000001
training:
  optimizer:
    name: Adam
    lr: 0.001
    betas: [0.5, 0.999]
    weight_decay: 0.0
  scheduler:
    name: StepLR
    step_size: 15
    gamma: 0.5
  clip_grad_norm: 5.0
