model:
  id: od/sarima
  params:
    order:
    - 6
    - 0
    - 0
    seasonal_order:
    - 1
    - 0
    - 0
    - 0
    n_threads: 8
  name: SARIMA
training:
  optimizer:
    name: none
    lr: 0.001
    weight_decay: 0.0
  clip_grad_norm: 0
  scheduler:
    name: none
runtime:
  device: cpu
